async 와 await
=============

- `async` · `await`
  - 프라미스 좀 더 편하게 사용

### `async` 함수
- `async` <sub>(키워드)</sub>
  - `function` 앞 위치
```javascript
async function f() {
  return 1;
}
```
- 항상 프라미스 반환
- 프라미스 아닌 값 반환 시
  - 이행 상태 프라미스로 감싸 반환
```javascript
async function f() {
  return 1;
}

f().then(alert); // 1
```
- 명시적으로 프라미스 반환 가능
  - 결과 동일
```javascript
async function f() {
  return Promise.resolve(1);
}

f().then(alert); // 1
```

### `await`
- 문법
```javascript
// async 함수 안에서만 동작
let value = await promise;
```

##### JS : `await` <sub>(키워드)</sub> 도달 시
1. 프라미스 처리 대기
2. 프라미스 처리 완료 시
    - 결과 반환 · 실행 재개
```javascript
async function f() {

  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("완료!"), 1000)
  });

  // 1. 프라미스 이행 완료 때까지 대기
  // 2. 프라미스 처리 후 실행 재개
  //    - 프라미스 result 값 → result (변수) 할당
  let result = await promise;

  alert(result);
}

// 1초 후
// - "완료!" 출력
f();
```

##### 프라미스 처리 대기 중
- 엔진 : 다른 일 수행 <sub>(CPU 리소스 낭비 X)</sub>
  - 다른 스크립트 실행
  - 이벤트 처리
  - 기타 등등

##### `promise.then` 대비
- 가독성 ↑
- 사용 난이도 ↓

<img class="icon" src="../../images/commons/icons/triangle-exclamation-solid.svg" /> **일반 함수 : `await` X**

##### 일반 함수
- `await` 사용 시
  - 문법 에러 발생
```javascript
function f() {
  let promise = Promise.resolve(1);
  let result = await promise; // Syntax error
}
```

<br />

##### `showAvatar()` 예시 <sub>(프라미스 체이닝 챕터)</sub>
- `async` · `await` 사용해 다시 작성
  1. `.then` 호출 → `await`
  2. `function` 앞 : `async`
```javascript
async function showAvatar() {

  // JSON 읽기
  let response = await fetch('/article/promise-chaining/user.json');
  let user = await response.json();

  // github 사용자 정보 읽기
  let githubResponse = await fetch(`https://api.github.com/users/${user.name}`);
  let githubUser = await githubResponse.json();

  // 아바타 보여주기
  let img = document.createElement('img');
  img.src = githubUser.avatar_url;
  img.className = "promise-avatar-example";
  document.body.append(img);

  // 3초 대기
  await new Promise((resolve, reject) => setTimeout(resolve, 3000));

  img.remove();

  return githubUser;
}

showAvatar();
```

<img class="icon" src="../../images/commons/icons/circle-exclamation-solid.svg" /> **`await` : 최상위 레벨 코드 X**

```javascript
// 최상위 레벨 코드에서 사용 시
// - 문법 에러 발생
let response = await fetch('/article/promise-chaining/user.json');
let user = await response.json();
```

##### 트릭
- 익명 `async` 함수 <sub>(코드 감싸기)</sub>
```javascript
(async () => {
  let response = await fetch('/article/promise-chaining/user.json');
  let user = await response.json();
  ...
})();
```

<img class="icon" src="../../images/commons/icons/circle-exclamation-solid.svg" /> **`await` : `thenable` <sub>(객체)</sub> 사용 가능**

##### 서드파티 객체
- 프라미스 미제공
  - 프라미스 호환 객체 제공
- `.then` <sub>(메서드)</sub> 지원
  - `await` 함께 사용 가능
```javascript
class Thenable {
  constructor(num) {
    this.num = num;
  }
  then(resolve, reject) {
    alert(resolve);

    // 1초 후 이행
    // - result : this.num * 2
    setTimeout(() => resolve(this.num * 2), 1000); // (*)
  }
};

async function f() {
  // 1초 후
  // - result (변수) : 2
  let result = await new Thenable(1);
  alert(result);
}

f();
```

##### `await` : 객체 <sub>(`.then` 구현 · 프라미스 X)</sub> 전달 시
1. `.then` <sub>(메서드)</sub> 호출
    - 인수 제공 <sub>(내장 함수)</sub>
      - `resolve`
      - `reject`
    - `Promise executor` 작업 동일
2. 인수 <sub>(`resolve` · `reject`)</sub> 중 하나 호출 대기
    - 호출 결과 함께 다음 작업 진행

<img class="icon" src="../../images/commons/icons/circle-exclamation-solid.svg" /> **async 클래스 메서드**

- `async` 클래스 메서드 선언
  - 메서드명 앞 `async`
```javascript
class Waiter {
  async wait() {
    return await Promise.resolve(1);
  }
}

new Waiter()
  .wait()
  .then(alert); // 1
```
- `async` 함수 · 메서드 <sub>(동일)</sub>
  - 프라미스 반환
  - `await` 사용 가능

### 에러 핸들링

##### 프라미스 정상 이행
- `await promise`
  - `result` <sub>(프라미스 객체 내)</sub> 저장 값 반환

##### 프라미스 거부
- 에러 던져짐
  - `throw` <sub>(문)</sub> 유사
```javascript
async function f() {
  await Promise.reject(new Error("에러 발생!"));
}

// 동일 코드
async function f() {
  throw new Error("에러 발생!");
}
```
- 프라미스 거부 전
  - 약간의 시간 지체 발생 경우 有
- `await`
  - 에러 던지기 전 지연 발생

##### `await` 가 던진 에러
- 에러 잡기 가능 <sub>(`try…catch`)</sub>
```javascript
async function f() {

  try {
    let response = await fetch('http://유효하지-않은-주소');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
```

##### 에러 발생 시
- 제어 흐름 → `catch` <sub>(블록)</sub>
- 코드 여러 줄 감싸기 <sub>(`try`)</sub>
```javascript
async function f() {

  try {
    let response = await fetch('http://유효하지-않은-주소');
    let user = await response.json();
  } catch(err) {
    // fetch와 response.json에서 발행한 에러 모두를 여기서 잡습니다.
    alert(err);
  }
}

f();
```

##### `try…catch` 부재 시
- `.catch` 추가
  - 거부 프라미스 처리
```javascript
async function f() {
  let response = await fetch('http://유효하지-않은-주소');
}

// f()
// - 거부 상태 프라미스
f().catch(alert); // TypeError: failed to fetch // (*)
```

##### `.catch` 미추가 시
- 미처리 프라미스 에러 발생
  - `unhandledrejection` 사용
    - 전역 이벤트 핸들러